### ISSUE TITLE
Expected Valid Header Issue

### ISSUE THREAD

**Issue by totoroyyb** [Relfos/lunar_parser#8]
I got a "Expected a Valid Header error" when I am trying to parse string like below
``` yaml
layout: list
title: iDEX Activities
slug: activities
description: >
  This page is for blogging activities of iDEX.
```
The plain text is
```
"layout: list\r\ntitle: iDEX Activities\r\nslug: activities\r\ndescription: >\r\n  This page is for blogging activities of iDEX."
```

I do believe it is a valid yaml as a YAML Front Matter in markdown file, but I cannot figure the problem.
